// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.Ct
{
    public static class CtConfig
    {
        public static Task<CtConfigResult> InvokeAsync(CtConfigArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<CtConfigResult>("ct:index/ctConfig:ctConfig", args ?? new CtConfigArgs(), options.WithDefaults());

        public static Output<CtConfigResult> Invoke(CtConfigInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<CtConfigResult>("ct:index/ctConfig:ctConfig", args ?? new CtConfigInvokeArgs(), options.WithDefaults());
    }


    public sealed class CtConfigArgs : Pulumi.InvokeArgs
    {
        [Input("content", required: true)]
        public string Content { get; set; } = null!;

        [Input("platform")]
        public string? Platform { get; set; }

        [Input("prettyPrint")]
        public bool? PrettyPrint { get; set; }

        [Input("snippets")]
        private List<string>? _snippets;
        public List<string> Snippets
        {
            get => _snippets ?? (_snippets = new List<string>());
            set => _snippets = value;
        }

        [Input("strict")]
        public bool? Strict { get; set; }

        public CtConfigArgs()
        {
        }
    }

    public sealed class CtConfigInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        [Input("platform")]
        public Input<string>? Platform { get; set; }

        [Input("prettyPrint")]
        public Input<bool>? PrettyPrint { get; set; }

        [Input("snippets")]
        private InputList<string>? _snippets;
        public InputList<string> Snippets
        {
            get => _snippets ?? (_snippets = new InputList<string>());
            set => _snippets = value;
        }

        [Input("strict")]
        public Input<bool>? Strict { get; set; }

        public CtConfigInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class CtConfigResult
    {
        public readonly string Content;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Platform;
        public readonly bool? PrettyPrint;
        public readonly string Rendered;
        public readonly ImmutableArray<string> Snippets;
        public readonly bool? Strict;

        [OutputConstructor]
        private CtConfigResult(
            string content,

            string id,

            string? platform,

            bool? prettyPrint,

            string rendered,

            ImmutableArray<string> snippets,

            bool? strict)
        {
            Content = content;
            Id = id;
            Platform = platform;
            PrettyPrint = prettyPrint;
            Rendered = rendered;
            Snippets = snippets;
            Strict = strict;
        }
    }
}
