// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ct

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func CtConfig(ctx *pulumi.Context, args *CtConfigArgs, opts ...pulumi.InvokeOption) (*CtConfigResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv CtConfigResult
	err := ctx.Invoke("ct:index/ctConfig:ctConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking ctConfig.
type CtConfigArgs struct {
	Content     string   `pulumi:"content"`
	Platform    *string  `pulumi:"platform"`
	PrettyPrint *bool    `pulumi:"prettyPrint"`
	Snippets    []string `pulumi:"snippets"`
	Strict      *bool    `pulumi:"strict"`
}

// A collection of values returned by ctConfig.
type CtConfigResult struct {
	Content string `pulumi:"content"`
	// The provider-assigned unique ID for this managed resource.
	Id          string   `pulumi:"id"`
	Platform    *string  `pulumi:"platform"`
	PrettyPrint *bool    `pulumi:"prettyPrint"`
	Rendered    string   `pulumi:"rendered"`
	Snippets    []string `pulumi:"snippets"`
	Strict      *bool    `pulumi:"strict"`
}

func CtConfigOutput(ctx *pulumi.Context, args CtConfigOutputArgs, opts ...pulumi.InvokeOption) CtConfigResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (CtConfigResult, error) {
			args := v.(CtConfigArgs)
			r, err := CtConfig(ctx, &args, opts...)
			var s CtConfigResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(CtConfigResultOutput)
}

// A collection of arguments for invoking ctConfig.
type CtConfigOutputArgs struct {
	Content     pulumi.StringInput      `pulumi:"content"`
	Platform    pulumi.StringPtrInput   `pulumi:"platform"`
	PrettyPrint pulumi.BoolPtrInput     `pulumi:"prettyPrint"`
	Snippets    pulumi.StringArrayInput `pulumi:"snippets"`
	Strict      pulumi.BoolPtrInput     `pulumi:"strict"`
}

func (CtConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CtConfigArgs)(nil)).Elem()
}

// A collection of values returned by ctConfig.
type CtConfigResultOutput struct{ *pulumi.OutputState }

func (CtConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CtConfigResult)(nil)).Elem()
}

func (o CtConfigResultOutput) ToCtConfigResultOutput() CtConfigResultOutput {
	return o
}

func (o CtConfigResultOutput) ToCtConfigResultOutputWithContext(ctx context.Context) CtConfigResultOutput {
	return o
}

func (o CtConfigResultOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v CtConfigResult) string { return v.Content }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o CtConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v CtConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o CtConfigResultOutput) Platform() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CtConfigResult) *string { return v.Platform }).(pulumi.StringPtrOutput)
}

func (o CtConfigResultOutput) PrettyPrint() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v CtConfigResult) *bool { return v.PrettyPrint }).(pulumi.BoolPtrOutput)
}

func (o CtConfigResultOutput) Rendered() pulumi.StringOutput {
	return o.ApplyT(func(v CtConfigResult) string { return v.Rendered }).(pulumi.StringOutput)
}

func (o CtConfigResultOutput) Snippets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v CtConfigResult) []string { return v.Snippets }).(pulumi.StringArrayOutput)
}

func (o CtConfigResultOutput) Strict() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v CtConfigResult) *bool { return v.Strict }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(CtConfigResultOutput{})
}
